### ISSUE TITLE
Other sync options: Google Drive, Dropbox, Nextcloud (regular, non-WebDAV)?

### ISSUE THREAD

**Issue by spiral6** [redsolver/noteless#3]
Allowing for other sync options using OAuth2 to authenticate or with integrated account support on Android would be pretty nice.

**Comment by redsolver** [comment]
Quick note: You can now specify a custom data directory under Android (https://github.com/redsolver/notable-mobile/commit/be5abfd5734592af13391fdce71cbc3564ce1b13), which allows to use basically any other external sync app.

**Comment by spiral6** [comment]
Unfortunately this only works with apps like FolderSync, but not with apps like Google Drive (which does not use the physical filesystem).

**Comment by redsolver** [comment]
I decided to drop support for syncing notes directly via the app in the new release, because it's very hard to implement it right and there are a lot better apps for it which primary feature is synchronisation. Maybe someday it will return, but for now I recommend using an external data directory and using a third-party sync app for Android like [Syncthing](https://syncthing.net/) or FolderSync for other cloud services.

Also, there are a lot of cloud services out there and I don't want to implement every single protocol or API they offer, because I think that's beyond the scope of this app when there are working alternatives.
