### ISSUE TITLE
Preview not loading

### ISSUE THREAD

**Issue by mimavox** [redsolver/noteless#32]
Cannot load preview, even for very simple notes. Loader icon just spins forever.

App version: 0.1.8, build 18
Device: Kindle Fire HDX 8.9
OS: Android 4.4 (Fire OS 4.5.5.3)

(The device/OS is of course rather old. Don't know if it's supposed to work on legacy devices? Rest of the app works fine.)

**Comment by redsolver** [comment]
I just tried it out on an Android 4.4 Emulator and could reproduce the issue. It is caused because flutter platform views (which are required for the preview browser) are only supported on Android Version 5.0 and up. Because of this I will disable the preview feature if the app is running on an Android 4.4 device. That's of course not a perfect solution, but it's still better than dropping support for legacy devices i hope.

**Comment by redsolver** [comment]
changed in https://github.com/redsolver/noteless/commit/7023336aba4941dce76733c01bd85c8fee34606e
