### ISSUE TITLE
Images with space in their filename are not displayed

### ISSUE THREAD

**Issue by cba85** [redsolver/noteless#36]
Hello,

Because I use Notable on my laptop, I've tried your app to open my "Notable" markdown files and I really like it! Thank you!

I've noticed an issue. If I try to display an image with a space in its filename, the image does not render.

```
![](@attachment/Screenshot 2020-08-08 at 20.33.23.png)

```

Thank you again for your useful app!

**Comment by redsolver** [comment]
Thank you for the nice words!

It seems like the markdown-to-html library I'm using doesn't support spaces in links (https://github.com/dart-lang/markdown).  I will analyze the library in the next days and try to fix it.

**Comment by cba85** [comment]
I understand 😊
Dart seems to be a cool language to use, but it is a new language and it's not really stable yet. I hope they will fix this issue on the dependency you use for this project.
Thanks for the reply!

**Comment by redsolver** [comment]
I analyzed the library: It's not a bug, the behavior is correct. Noteless uses the GitHub Web Markdown spec and as you can see, it doesn't support spaces in links or image filenames:

[Title](my link)

![Title](my link)

However, Noteless aims to be compatible with Notable, so I will fork the markdown library and modify this behavior. Should be fixed in the next release in the coming week.

**Comment by redsolver** [comment]
Forking went faster than expected :smile: 

@cba85 This should now be fixed in the brand-new version 1.1.1: https://github.com/redsolver/noteless/releases/tag/v1.1.1

Please let me know if it works, thank you!

**Comment by cba85** [comment]
Hello,

I'm happy to say it perfectly works now!

You fixed the problem so fast it's impressive! Thank you very much!! ✌️
