### ISSUE TITLE
Support for the Android 11 permission system

### ISSUE THREAD

**Issue by juanfcocontreras** [redsolver/noteless#63]
Until Android 11, it was possible to use a folder to sync out of the application data scope. As of Android 11 this seems to have changed:

https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c

The problem is that currently neither Noteless can save its notes outside its data folder, nor FolderSync can access Noteless' notes to sync them, so the sync part does not work in Android 11.

Any idea to try to solve it?

**Comment by John3** [comment]
I have the exact same issue, likely is android 11.

**Comment by redsolver** [comment]
I recommend not to update to Android 11 for now. Looks like https://developer.android.com/guide/topics/providers/content-provider-basics is the only way to share app data between multiple apps in Android 11, but it's quite complicated and needs to be supported by all participating apps.

**Comment by Ledarium** [comment]
> Looks like https://developer.android.com/guide/topics/providers/content-provider-basics is the only way to share app data between multiple apps in Android 11

I am not sure about this, as for example Markor app can access any directory on sdcard, without needing to be supported by another apps. It uses storage access framework, which could be seen here https://github.com/gsantner/markor/issues/547. As far as I can see this method is also used in many other applications.
Another example is simpletask app, where developer used special permission to have access to whole filesystem, related issue here https://github.com/mpcjanssen/simpletask-android/issues/1100. This is only available since API level 30 though.

Please consider implementing one of these methods to access files in other directories, because simply not updating to Android 11 is clearly not a long-term solution.

**Comment by redsolver** [comment]
Unfortunately, using the SAF (storage access framework) from Flutter is not yet possible. I couldn't find a plugin supporting it and other developers seem to struggle with it too: https://stackoverflow.com/questions/65355464/is-there-a-way-to-access-android-storage-access-framwork-saf-from-dart

Also, I think it makes more sense to implement some workaround to access the whole filesystem in Syncthing and FolderSync, because this would also give these apps access to Noteless' data directory.

**Comment by DanielJutz** [comment]
I second the suggestion to use SAF. I'm running Android 9 and I would like to save the notes to the micro sd card. This is where I store all my syncthing folders due to size constraints and I would like to keep it consolidated. I do not know the flutter limitations though.

**Comment by dmotte** [comment]
I think that using SAF would solve a lot of problems in one simple move. It would provide Nextcloud integration, GoogleDrive integration, Termux integration, external storage integration, basically integration with **every possible cloud service** or app which also uses SAF... The notes could then be synchronized automagically **without any effort** from the Noteless app 🙂 it would be a great thing and would also **improve security**, since Noteless won't require **storage permission** anymore!

**Comment by redsolver** [comment]
@dmotte Can you point me to a resource which explains how to integrate this?

**Comment by dmotte** [comment]
Unfortunately i don't know Flutter or Dart. I have never used them, although i think that they are great technologies. Maybe this package can help? https://pub.dev/packages/file_picker (sorry if it's not related, just searched a few minutes)

**Comment by dmotte** [comment]
Ok, i have another useful information:

I also use the [AuthPass](authpass.app) app (written in Flutter). With it, I am able to use a **Google Drive folder** to store my passwords database. It works like a charm and i have my `passwords.kdbx` file automatically synchronized both on my smartphone and my PC.
Just found out that [the AuthPass app uses the `file_picker_writable` package](https://github.com/authpass/authpass/blob/master/authpass/pubspec.yaml).

**Comment by redsolver** [comment]
@dmotte Thank you, this is extremely useful!

**Comment by redsolver** [comment]
I just implemented and tested the changes needed for Noteless to work on Android 11. Because this is a very experimental change, I did not publish a full release yet and instead compiled a beta APK. It would be great if everyone here with Android 11 could test the change, but please be aware that it is **experimental** and could make your notes disappear in the worst case.

Beta APK Download: https://siasky.net/AAAmLR60_Yh3ljfvVI5poZjWmUlWa_-yl9zWH-VEbepfsQ

**Comment by everylake** [comment]
Testing on Pixel 3 / Android 11 and it works perfectly! 

Thank you, thank you, thank you! 👏

**Comment by ivanvenosdel** [comment]
I also have a Pixel 3 / Android 11. I was able to turn on "use external storage", which prompted me for the permission but then when trying to change the location from `Android/data/net.redsolver.noteless/files` to a location that another app can access, it doesn't let me browse outside of "net.redsolver.noteless".

**Comment by redsolver** [comment]
@ivanvenosdel Could you please verify that you're using Version `1.4.0`? It's shown in the top left corner of the sidebar

**Comment by ivanvenosdel** [comment]
@redsolver I was not. Will try the install again and get back to you.

**Comment by everylake** [comment]
> @redsolver I was not. Will try the install again and get back to you.

You have to uninstall the old version, updating is not possible.

**Comment by ivanvenosdel** [comment]
Yeah, learned that. The beta version worked for me! I created and saved a new note and confirmed it got saved in the external location, alongside the tutorial files.

**Comment by sudoandros** [comment]
Hey, potentially new user here :) Look like a really good app but can't use because of the issue discussed. Tried to test your beta APK on Galaxy M31. Now I am able to choose external directory but nothing happens after that. I still see only the default tutorial notes and none of my notes that are located inside the chosen directory.

**Comment by redsolver** [comment]
@sudoandros Noteless reads and saves your Markdown files from the `notes/` subdirectory in the selected external directory

**Comment by sudoandros** [comment]
Oh 😅 Ok, got it, it works. Thanks for quick response!

**Comment by anthonyajumelles** [comment]
> I just implemented and tested the changes needed for Noteless to work on Android 11. Because this is a very experimental change, I did not publish a full release yet and instead compiled a beta APK. It would be great if everyone here with Android 11 could test the change, but please be aware that it is **experimental** and could make your notes disappear in the worst case.
> 
> Beta APK Download: https://siasky.net/AAAmLR60_Yh3ljfvVI5poZjWmUlWa_-yl9zWH-VEbepfsQ

So far so good on LineageOS w/ MicroG on Pixel 4a 5G. Syncthing enabled and nothing has gone missing after a bit of testing.

**Comment by xeor** [comment]
Nice to see this issue solved :) when will the new version hit the play store? Or has everyone just settled on using the beta apk 🤔

**Comment by redsolver** [comment]
There will be a release with this and some other new features soon

**Comment by redsolver** [comment]
I just published Version 1.4.6 which contains the new permission system
Direct APK download available now: https://github.com/redsolver/noteless/releases/tag/v1.4.6
Available in about an hour in the SkyDroid App Store: https://to.skydroid.app/noteless.redsolver
Available in some days on F-Droid and Google Play
